main: com.github.djkingcraftero89.TH_TempFly.TH_TempFly
version: ${project.version}
name: TH_TempFly
authors: [JuanCorso]
description: Temporary fly plugin with SQL and Redis support for multi-server networks
api-version: 1.20
softdepend: [PlaceholderAPI]

commands:
  tempfly:
    description: Manage temporary fly time for players
    usage: "/tempfly <give|add|remove|check|reload> [player] [time]"
    aliases: [tfly]
    permission: thtempfly.use
  fly:
    description: Toggle flight mode for yourself
    usage: "/fly"
    permission: thtempfly.fly.use
  atempfly:
    description: Admin debug command for TempFly
    usage: "/atempfly debug <true|false>"
    permission: thtempfly.admin

permissions:
  thtempfly.use:
    description: Allows using /tempfly base command
    default: op
  thtempfly.admin:
    description: Allows managing other players' fly time, reload config, and debug mode
    default: op
  thtempfly.fly:
    description: Allows player to have temporary fly
    default: true
  thtempfly.fly.use:
    description: Allows player to use /fly command to toggle flight
    default: true
  thtempfly.fly.infinite:
    description: Allows player to have infinite fly time
    default: op