main: com.github.djkingcraftero89.TH_TempFly.TH_TempFly
version: ${project.version}
name: TH_TempFly
authors: [JuanCorso]
description: Temporary fly plugin with SQL, Redis, and WorldGuard region restrictions for multi-server networks
api-version: 1.21
softdepend: [PlaceholderAPI, WorldGuard, Vulcan]

# Paper's native library loader - automatically downloads from Maven Central
libraries:
  # Database libraries
  - com.zaxxer:HikariCP:5.1.0
  - org.slf4j:slf4j-api:2.0.9
  - org.xerial:sqlite-jdbc:3.46.0.0
  - com.mysql:mysql-connector-j:8.4.0
  - com.google.protobuf:protobuf-java:3.25.1

  # Redis libraries
  - io.lettuce:lettuce-core:6.3.2.RELEASE
  - io.netty:netty-common:4.1.107.Final
  - io.netty:netty-handler:4.1.107.Final
  - io.netty:netty-transport:4.1.107.Final
  - io.netty:netty-buffer:4.1.107.Final
  - io.netty:netty-codec:4.1.107.Final
  - io.netty:netty-resolver:4.1.107.Final
  - io.netty:netty-transport-native-unix-common:4.1.107.Final
  - io.projectreactor:reactor-core:3.6.4
  - org.reactivestreams:reactive-streams:1.0.4

commands:
  tempfly:
    description: Manage temporary fly time for players
    usage: "/tempfly <give|add|remove|check|reload|version|migrate> [player] [time]"
    aliases: [tfly]
    permission: thtempfly.use
  fly:
    description: Toggle flight mode or manage flight for yourself
    usage: "/fly [toggle|on|off|check]"
    permission: thtempfly.fly.use
  atempfly:
    description: Admin debug command for TempFly
    usage: "/atempfly debug <true|false>"
    permission: thtempfly.admin

permissions:
  thtempfly.use:
    description: Allows using /tempfly base command
    default: op
  thtempfly.admin:
    description: Allows managing other players' fly time, reload config, and debug mode
    default: op
  thtempfly.fly:
    description: Allows player to have temporary fly
    default: true
  thtempfly.fly.use:
    description: Allows player to use /fly command to toggle flight
    default: true
  thtempfly.fly.infinite:
    description: Allows player to have infinite fly time
    default: op
  thtempfly.fly.bypass:
    description: Allows player to bypass flight restrictions in blocked worlds and regions
    default: op